name: App Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Linter
        run: ./gradlew ktlintCheck

      - name: Build Project
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test