name: App Format

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Format Code
        run: ./gradlew ktlintFormat

      - name: Run Tests
        run: ./gradlew test